build-test:
	docker build -t marciodojr/php-fpm:82-functions-dev-test .
build:
	docker build -t marciodojr/php-fpm:82-functions-dev .
build-test:
	docker build -t marciodojr/php-fpm:82-functions-dev-test .
push:
	docker push marciodojr/php-fpm:82-functions-dev
